# Generated by Django 5.2.6 on 2025-09-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
    ]
