# Generated by Django 5.2.6 on 2025-09-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_add_missing_fields_clean'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='botconfiguration',
            new_name='dashboard_b_risk_to_5d4eeb_idx',
            old_name='dashboard_b_risk_to_idx',
        ),
        migrations.RenameIndex(
            model_name='botconfiguration',
            new_name='dashboard_b_mev_pro_02a551_idx',
            old_name='dashboard_b_mev_pro_idx',
        ),
    ]
