# Generated by Django 5.2.6 on 2025-11-03 14:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertradingaccount',
            name='current_balance_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Current virtual balance in USD', max_digits=20),
        ),
    ]
