# Generated by Django 5.2.6 on 2025-11-23 11:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_trading", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paperposition",
            name="average_entry_price_usd",
            field=models.DecimalField(
                decimal_places=18,
                default=Decimal("0"),
                help_text="Average entry price in USD",
                max_digits=26,
            ),
        ),
        migrations.AlterField(
            model_name="paperposition",
            name="current_price_usd",
            field=models.DecimalField(
                decimal_places=18,
                default=Decimal("0"),
                help_text="Current market price",
                max_digits=26,
            ),
        ),
    ]
