# Generated by Django 5.2.6 on 2025-11-03 17:22

from decimal import Decimal
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0002_alter_papertradingaccount_current_balance_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='max_trade_size_usd',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('1000.00'),
                help_text='Maximum trade size in USD (absolute limit)',
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('10')),
                    django.core.validators.MaxValueValidator(Decimal('100000'))
                ]
            ),
        ),
    ]