# Generated by Django 5.2.6 on 2025-11-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_trading", "0002_alter_paperposition_average_entry_price_usd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="papertrade",
            name="execution_dex",
            field=models.CharField(
                choices=[
                    ("uniswap_v3", "Uniswap V3"),
                    ("uniswap_v2", "Uniswap V2"),
                    ("sushiswap", "SushiSwap"),
                    ("curve", "Curve Finance"),
                ],
                db_index=True,
                default="uniswap_v3",
                help_text="DEX where trade was executed (Uniswap V3, SushiSwap, Curve)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="papertrade",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="AI trade context (intel level, confidence, reasoning, DEX comparison)",
            ),
        ),
        migrations.AddIndex(
            model_name="papertrade",
            index=models.Index(
                fields=["execution_dex"], name="paper_trade_executi_aa30a3_idx"
            ),
        ),
    ]
