# Generated by Django 5.2.6 on 2025-10-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0003_fix_position_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='AI trade context (intel level, confidence, reasoning, etc.)'),
        ),
    ]
