# Generated by Django 5.2.6 on 2025-11-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "paper_trading",
            "0003_papertrade_execution_dex_alter_papertrade_metadata_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="paperposition",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="paperposition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_open", True)),
                fields=("account", "token_address"),
                name="unique_open_position_per_token",
            ),
        ),
    ]
