# Generated by Django 5.2.6 on 2025-11-09 14:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0004_fix_decimal_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperOrder',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique order identifier', primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('LIMIT_BUY', 'Limit Buy'), ('LIMIT_SELL', 'Limit Sell'), ('STOP_LIMIT_BUY', 'Stop-Limit Buy'), ('STOP_LIMIT_SELL', 'Stop-Limit Sell'), ('TRAILING_STOP', 'Trailing Stop')], help_text='Type of order', max_length=20)),
                ('token_address', models.CharField(help_text='Token contract address', max_length=42)),
                ('token_symbol', models.CharField(help_text='Token symbol (e.g., AAVE, LINK)', max_length=20)),
                ('token_name', models.CharField(blank=True, help_text='Token full name', max_length=100)),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text='Order size in USD', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('amount_token', models.DecimalField(blank=True, decimal_places=18, help_text='Order size in tokens (calculated from amount_usd)', max_digits=36, null=True)),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=8, help_text='Trigger price for limit orders and stop-limit orders', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('limit_price', models.DecimalField(blank=True, decimal_places=8, help_text='Limit price for stop-limit orders (execution price)', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('stop_price', models.DecimalField(blank=True, decimal_places=8, help_text='Stop price for stop-limit orders (same as trigger_price)', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('trail_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Trailing stop percentage (e.g., 5.0 = 5% trail)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('50.0'))])),
                ('trail_amount', models.DecimalField(blank=True, decimal_places=8, help_text='Trailing stop fixed amount (alternative to trail_percent)', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('highest_price', models.DecimalField(blank=True, decimal_places=8, help_text='Highest price seen (for trailing stops)', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('current_stop_price', models.DecimalField(blank=True, decimal_places=8, help_text='Current trailing stop price (updated as price rises)', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TRIGGERED', 'Triggered'), ('PARTIALLY_FILLED', 'Partially Filled'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], default='PENDING', help_text='Current order status', max_length=20)),
                ('filled_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount filled in USD (for partial fills)', max_digits=20)),
                ('filled_amount_token', models.DecimalField(decimal_places=18, default=Decimal('0'), help_text='Amount filled in tokens (for partial fills)', max_digits=36)),
                ('average_fill_price', models.DecimalField(blank=True, decimal_places=8, help_text='Average execution price', max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Order placement timestamp')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Order expiration timestamp (optional)', null=True)),
                ('triggered_at', models.DateTimeField(blank=True, help_text='Timestamp when stop price was triggered', null=True)),
                ('filled_at', models.DateTimeField(blank=True, help_text='Timestamp when order was filled', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Timestamp when order was cancelled', null=True)),
                ('notes', models.TextField(blank=True, help_text='User notes or order description')),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed')),
                ('account', models.ForeignKey(help_text='Paper trading account that placed this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='paper_trading.papertradingaccount')),
                ('related_trade', models.ForeignKey(blank=True, help_text='Link to the trade that executed this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_order', to='paper_trading.papertrade')),
            ],
            options={
                'verbose_name': 'Paper Order',
                'verbose_name_plural': 'Paper Orders',
                'db_table': 'paper_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'status'], name='paper_order_account_5efd27_idx'), models.Index(fields=['order_type', 'status'], name='paper_order_order_t_cd3bd8_idx'), models.Index(fields=['token_address', 'status'], name='paper_order_token_a_f3da6d_idx'), models.Index(fields=['status', 'created_at'], name='paper_order_status_9c8ca5_idx'), models.Index(fields=['expires_at'], name='paper_order_expires_511136_idx')],
            },
        ),
    ]
