# Generated by Django 5.2.6 on 2025-11-29 16:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_trading", "0004_alter_paperposition_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacktestRun",
            fields=[
                (
                    "backtest_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this backtest",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("SPOT", "Spot Buy"),
                            ("DCA", "Dollar Cost Averaging"),
                            ("GRID", "Grid Trading"),
                            ("TWAP", "Time-Weighted Average Price"),
                            ("VWAP", "Volume-Weighted Average Price"),
                        ],
                        help_text="Type of strategy to backtest",
                        max_length=20,
                    ),
                ),
                (
                    "token_symbol",
                    models.CharField(
                        help_text="Token symbol (e.g., ETH, WBTC)", max_length=20
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Start of backtest period"),
                ),
                ("end_date", models.DateTimeField(help_text="End of backtest period")),
                (
                    "interval",
                    models.CharField(
                        default="1h",
                        help_text="Data interval (e.g., 1h, 1d)",
                        max_length=10,
                    ),
                ),
                (
                    "initial_balance_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Starting balance in USD",
                        max_digits=28,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "strategy_params",
                    models.JSONField(
                        default=dict, help_text="Strategy-specific parameters"
                    ),
                ),
                (
                    "fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.30"),
                        help_text="Trading fee percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("10.00")),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        help_text="Current status of backtest",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error details if backtest failed",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When backtest was created"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When backtest completed", null=True
                    ),
                ),
                (
                    "data_points",
                    models.IntegerField(
                        default=0, help_text="Number of historical data points used"
                    ),
                ),
            ],
            options={
                "db_table": "paper_backtest_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "backtest_run",
                    models.OneToOneField(
                        help_text="Related backtest run",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="result",
                        serialize=False,
                        to="paper_trading.backtestrun",
                    ),
                ),
                (
                    "final_balance_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final balance in USD",
                        max_digits=28,
                    ),
                ),
                (
                    "profit_loss_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total profit or loss in USD",
                        max_digits=28,
                    ),
                ),
                (
                    "return_percent",
                    models.DecimalField(
                        decimal_places=2, help_text="Return percentage", max_digits=10
                    ),
                ),
                (
                    "total_fees_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total trading fees paid",
                        max_digits=28,
                    ),
                ),
                (
                    "num_trades",
                    models.IntegerField(default=0, help_text="Total number of trades"),
                ),
                (
                    "num_buys",
                    models.IntegerField(default=0, help_text="Number of buy trades"),
                ),
                (
                    "num_sells",
                    models.IntegerField(default=0, help_text="Number of sell trades"),
                ),
                (
                    "avg_entry_price",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0.00"),
                        help_text="Average entry price",
                        max_digits=28,
                    ),
                ),
                (
                    "win_rate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of winning trades",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "profit_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Gross profit / gross loss ratio",
                        max_digits=10,
                    ),
                ),
                (
                    "max_drawdown_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Maximum drawdown percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sharpe ratio (risk-adjusted return)",
                        max_digits=6,
                    ),
                ),
                (
                    "sortino_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sortino ratio (downside risk-adjusted return)",
                        max_digits=6,
                    ),
                ),
                (
                    "avg_holding_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average holding period in hours",
                        max_digits=10,
                    ),
                ),
                (
                    "max_consecutive_wins",
                    models.IntegerField(
                        default=0, help_text="Maximum consecutive winning trades"
                    ),
                ),
                (
                    "max_consecutive_losses",
                    models.IntegerField(
                        default=0, help_text="Maximum consecutive losing trades"
                    ),
                ),
                (
                    "trades_data",
                    models.JSONField(
                        default=list, help_text="Detailed list of all simulated trades"
                    ),
                ),
                (
                    "metrics_data",
                    models.JSONField(
                        default=dict, help_text="Additional metrics and statistics"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When result was created"
                    ),
                ),
            ],
            options={
                "db_table": "paper_backtest_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="backtestrun",
            index=models.Index(
                fields=["-created_at"], name="paper_backt_created_be2629_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backtestrun",
            index=models.Index(
                fields=["strategy_type", "-created_at"],
                name="paper_backt_strateg_603e26_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="backtestrun",
            index=models.Index(
                fields=["token_symbol", "-created_at"],
                name="paper_backt_token_s_e769e0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="backtestrun",
            index=models.Index(fields=["status"], name="paper_backt_status_0c1dfa_idx"),
        ),
        migrations.AddIndex(
            model_name="backtestresult",
            index=models.Index(
                fields=["-return_percent"], name="paper_backt_return__976f1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backtestresult",
            index=models.Index(
                fields=["-sharpe_ratio"], name="paper_backt_sharpe__d8b871_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backtestresult",
            index=models.Index(
                fields=["-win_rate_percent"], name="paper_backt_win_rat_715725_idx"
            ),
        ),
    ]
