# Generated by Django 5.2.6 on 2025-10-24 13:32

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0004_papertrade_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPilotLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique log identifier', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When adjustment was made')),
                ('adjustment_type', models.CharField(choices=[('POSITION_SIZE_INCREASE', 'Position Size Increase'), ('POSITION_SIZE_DECREASE', 'Position Size Decrease'), ('CONFIDENCE_INCREASE', 'Confidence Threshold Increase'), ('CONFIDENCE_DECREASE', 'Confidence Threshold Decrease'), ('FREQUENCY_INCREASE', 'Trading Frequency Increase'), ('FREQUENCY_DECREASE', 'Trading Frequency Decrease'), ('STOP_LOSS_TIGHTEN', 'Stop Loss Tightened'), ('STOP_LOSS_LOOSEN', 'Stop Loss Loosened'), ('TAKE_PROFIT_INCREASE', 'Take Profit Increased'), ('TAKE_PROFIT_DECREASE', 'Take Profit Decreased'), ('PAUSE_TRADING', 'Trading Paused'), ('RESUME_TRADING', 'Trading Resumed'), ('GAS_STRATEGY_ADJUST', 'Gas Strategy Adjusted'), ('RISK_TOLERANCE_ADJUST', 'Risk Tolerance Adjusted')], help_text='Type of adjustment made', max_length=50)),
                ('parameter_name', models.CharField(help_text='Name of the parameter adjusted', max_length=50)),
                ('old_value', models.DecimalField(decimal_places=4, help_text='Previous parameter value', max_digits=10)),
                ('new_value', models.DecimalField(decimal_places=4, help_text='New parameter value', max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, help_text='Percentage change', max_digits=7)),
                ('reason', models.TextField(help_text='Detailed explanation of why this adjustment was made')),
                ('trigger_metric', models.CharField(help_text="Metric that triggered adjustment (e.g., 'win_rate', 'drawdown')", max_length=50)),
                ('trigger_value', models.DecimalField(decimal_places=4, help_text='Value of the trigger metric', max_digits=10)),
                ('trigger_threshold', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Threshold value that was crossed', max_digits=10)),
                ('performance_before', models.JSONField(default=dict, help_text='Performance metrics before adjustment')),
                ('performance_after', models.JSONField(blank=True, default=dict, help_text='Performance metrics after adjustment (filled later)', null=True)),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending - Too early to tell'), ('POSITIVE', 'Positive - Improved performance'), ('NEUTRAL', 'Neutral - No significant change'), ('NEGATIVE', 'Negative - Worsened performance'), ('UNKNOWN', 'Unknown - Insufficient data')], default='PENDING', help_text='Evaluation of adjustment outcome', max_length=20)),
                ('outcome_evaluated_at', models.DateTimeField(blank=True, help_text='When the outcome was evaluated', null=True)),
                ('outcome_notes', models.TextField(blank=True, help_text='Additional notes on the outcome')),
                ('trades_since_adjustment', models.IntegerField(default=0, help_text='Number of trades executed since this adjustment')),
                ('market_conditions', models.JSONField(default=dict, help_text='Market conditions at time of adjustment')),
                ('confidence_in_adjustment', models.DecimalField(decimal_places=2, default=Decimal('50'), help_text="Auto Pilot's confidence in this adjustment (0-100)", max_digits=5)),
                ('is_reversal', models.BooleanField(default=False, help_text='Whether this reverses a previous adjustment')),
            ],
            options={
                'verbose_name': 'Auto Pilot Log',
                'verbose_name_plural': 'Auto Pilot Logs',
                'db_table': 'autopilot_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AutoPilotPerformanceSnapshot',
            fields=[
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique snapshot identifier', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When snapshot was taken')),
                ('current_parameters', models.JSONField(default=dict, help_text='Current parameter configuration at snapshot time')),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Win rate percentage', max_digits=5)),
                ('total_trades', models.IntegerField(default=0, help_text='Total trades executed')),
                ('winning_trades', models.IntegerField(default=0, help_text='Number of winning trades')),
                ('losing_trades', models.IntegerField(default=0, help_text='Number of losing trades')),
                ('total_pnl_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total profit/loss in USD', max_digits=20)),
                ('average_profit_per_trade', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Average profit per trade', max_digits=20)),
                ('average_win_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Average winning trade amount', max_digits=20)),
                ('average_loss_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Average losing trade amount', max_digits=20)),
                ('largest_win_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Largest winning trade', max_digits=20)),
                ('largest_loss_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Largest losing trade', max_digits=20)),
                ('max_drawdown_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Maximum drawdown percentage', max_digits=5)),
                ('sharpe_ratio', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Risk-adjusted return metric (Sharpe Ratio)', max_digits=6)),
                ('profit_factor', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Ratio of gross profit to gross loss', max_digits=6)),
                ('market_volatility', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Market volatility index at snapshot time (0-100)', max_digits=5)),
                ('avg_gas_price_gwei', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Average gas price in this period', max_digits=10)),
                ('market_trend', models.CharField(default='neutral', help_text='Market trend (bullish/bearish/neutral)', max_length=20)),
                ('market_conditions_detail', models.JSONField(default=dict, help_text='Detailed market conditions')),
                ('autopilot_active', models.BooleanField(default=False, help_text='Whether Auto Pilot was active during this period')),
                ('adjustments_made_count', models.IntegerField(default=0, help_text='Number of Auto Pilot adjustments made before this snapshot')),
                ('last_adjustment_type', models.CharField(blank=True, help_text='Type of most recent adjustment', max_length=50)),
                ('snapshot_period_hours', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Time period covered by this snapshot in hours', max_digits=6)),
                ('notes', models.TextField(blank=True, help_text='Optional notes or observations')),
            ],
            options={
                'verbose_name': 'Auto Pilot Performance Snapshot',
                'verbose_name_plural': 'Auto Pilot Performance Snapshots',
                'db_table': 'autopilot_performance_snapshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='paperaithoughtlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Thought Log', 'verbose_name_plural': 'AI Thought Logs'},
        ),
        migrations.AlterModelOptions(
            name='paperperformancemetrics',
            options={'ordering': ['-period_end'], 'verbose_name': 'Performance Metrics', 'verbose_name_plural': 'Performance Metrics'},
        ),
        migrations.AlterModelOptions(
            name='paperposition',
            options={'ordering': ['-opened_at'], 'verbose_name': 'Paper Position', 'verbose_name_plural': 'Paper Positions'},
        ),
        migrations.AlterModelOptions(
            name='paperstrategyconfiguration',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Strategy Configuration', 'verbose_name_plural': 'Strategy Configurations'},
        ),
        migrations.AlterModelOptions(
            name='papertrade',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paper Trade', 'verbose_name_plural': 'Paper Trades'},
        ),
        migrations.AlterModelOptions(
            name='papertradingaccount',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paper Trading Account', 'verbose_name_plural': 'Paper Trading Accounts'},
        ),
        migrations.AlterModelOptions(
            name='papertradingconfig',
            options={'verbose_name': 'Paper Trading Config', 'verbose_name_plural': 'Paper Trading Configs'},
        ),
        migrations.AlterModelOptions(
            name='papertradingsession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Paper Trading Session', 'verbose_name_plural': 'Paper Trading Sessions'},
        ),
        migrations.RemoveConstraint(
            model_name='paperposition',
            name='unique_open_position_per_token',
        ),
        migrations.RenameField(
            model_name='papertradingaccount',
            old_name='total_pnl_usd',
            new_name='total_profit_loss_usd',
        ),
        migrations.RemoveField(
            model_name='paperaithoughtlog',
            name='confidence_percent',
        ),
        migrations.RemoveField(
            model_name='paperaithoughtlog',
            name='opportunity_score',
        ),
        migrations.RemoveField(
            model_name='paperaithoughtlog',
            name='primary_reasoning',
        ),
        migrations.RemoveField(
            model_name='paperaithoughtlog',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='paperperformancemetrics',
            name='avg_execution_time_ms',
        ),
        migrations.RemoveField(
            model_name='paperperformancemetrics',
            name='avg_loss_usd',
        ),
        migrations.RemoveField(
            model_name='paperperformancemetrics',
            name='avg_slippage_percent',
        ),
        migrations.RemoveField(
            model_name='paperperformancemetrics',
            name='avg_win_usd',
        ),
        migrations.RemoveField(
            model_name='paperperformancemetrics',
            name='calculated_at',
        ),
        migrations.RemoveField(
            model_name='paperperformancemetrics',
            name='fast_lane_trades',
        ),
        migrations.RemoveField(
            model_name='paperperformancemetrics',
            name='fast_lane_win_rate',
        ),
        migrations.RemoveField(
            model_name='paperperformancemetrics',
            name='metrics_id',
        ),
        migrations.RemoveField(
            model_name='paperperformancemetrics',
            name='smart_lane_trades',
        ),
        migrations.RemoveField(
            model_name='paperperformancemetrics',
            name='smart_lane_win_rate',
        ),
        migrations.RemoveField(
            model_name='paperperformancemetrics',
            name='total_gas_fees_usd',
        ),
        migrations.AlterUniqueTogether(
            name='paperposition',
            unique_together={('account', 'token_address', 'is_open')},
        ),
        migrations.RemoveField(
            model_name='papertradingaccount',
            name='eth_balance',
        ),
        migrations.RemoveField(
            model_name='papertradingaccount',
            name='failed_trades',
        ),
        migrations.RemoveField(
            model_name='papertradingaccount',
            name='reset_count',
        ),
        migrations.RemoveField(
            model_name='papertradingaccount',
            name='successful_trades',
        ),
        migrations.RemoveField(
            model_name='papertradingaccount',
            name='total_fees_paid_usd',
        ),
        migrations.RemoveField(
            model_name='papertradingaccount',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='papertradingsession',
            name='config_snapshot',
        ),
        migrations.RemoveField(
            model_name='papertradingsession',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='papertradingsession',
            name='ending_balance_usd',
        ),
        migrations.RemoveField(
            model_name='papertradingsession',
            name='error_count',
        ),
        migrations.RemoveField(
            model_name='papertradingsession',
            name='last_error_message',
        ),
        migrations.RemoveField(
            model_name='papertradingsession',
            name='last_error_time',
        ),
        migrations.RemoveField(
            model_name='papertradingsession',
            name='last_heartbeat',
        ),
        migrations.RemoveField(
            model_name='papertradingsession',
            name='name',
        ),
        migrations.RemoveField(
            model_name='papertradingsession',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='papertradingsession',
            name='session_pnl_usd',
        ),
        migrations.RemoveField(
            model_name='papertradingsession',
            name='starting_balance_usd',
        ),
        migrations.RemoveField(
            model_name='papertradingsession',
            name='total_trades_executed',
        ),
        migrations.AddField(
            model_name='paperaithoughtlog',
            name='reasoning',
            field=models.TextField(default='', help_text='AI reasoning for the decision'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paperaithoughtlog',
            name='risk_assessment',
            field=models.TextField(blank=True, help_text='Risk analysis'),
        ),
        migrations.AddField(
            model_name='paperperformancemetrics',
            name='average_loss_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Average losing trade amount', max_digits=20),
        ),
        migrations.AddField(
            model_name='paperperformancemetrics',
            name='average_win_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Average winning trade amount', max_digits=20),
        ),
        migrations.AddField(
            model_name='paperperformancemetrics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 24, 13, 31, 4, 986938, tzinfo=datetime.timezone.utc), help_text='When metrics were calculated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paperperformancemetrics',
            name='metric_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique metric identifier', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='paperposition',
            name='token_name',
            field=models.CharField(blank=True, help_text='Token name', max_length=100),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='adaptation_aggressiveness',
            field=models.CharField(choices=[('CONSERVATIVE', 'Conservative - Small adjustments'), ('MODERATE', 'Moderate - Balanced learning'), ('AGGRESSIVE', 'Aggressive - Fast adaptation')], default='MODERATE', help_text='How aggressively Auto Pilot adapts parameters', max_length=20),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='adjustment_cooldown_minutes',
            field=models.IntegerField(default=30, help_text='Minimum minutes between Auto Pilot adjustments', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='auto_disable_after_failures',
            field=models.IntegerField(default=5, help_text='Disable Auto Pilot after N consecutive bad adjustments', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='autopilot_adjustments_count',
            field=models.IntegerField(default=0, help_text='Total number of adjustments made by Auto Pilot'),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='autopilot_enabled',
            field=models.BooleanField(default=False, help_text='Enable Auto Pilot for intelligent parameter adaptation'),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='autopilot_last_adjustment',
            field=models.DateTimeField(blank=True, help_text='Timestamp of most recent Auto Pilot adjustment', null=True),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='autopilot_started_at',
            field=models.DateTimeField(blank=True, help_text='When Auto Pilot was first activated', null=True),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='learning_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1000'), help_text='Learning rate for parameter adjustments (0.0001 - 1.0)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('1.0'))]),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='max_confidence_threshold_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('95.0'), help_text='Maximum confidence threshold Auto Pilot can set', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('50')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='max_daily_adjustments',
            field=models.IntegerField(default=10, help_text='Maximum parameter adjustments per day', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='max_position_size_percent_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.0'), help_text='Maximum position size Auto Pilot can set', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('50'))]),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='min_confidence_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.0'), help_text='Minimum confidence threshold Auto Pilot can set', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('10')), django.core.validators.MaxValueValidator(Decimal('95'))]),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='min_position_size_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Minimum position size Auto Pilot can set', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('25'))]),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='performance_window_trades',
            field=models.IntegerField(default=20, help_text='Number of recent trades to consider for performance analysis', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='papertradingaccount',
            name='description',
            field=models.TextField(blank=True, help_text='Account description'),
        ),
        migrations.AddField(
            model_name='papertradingaccount',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, help_text='Last activity timestamp'),
        ),
        migrations.AddField(
            model_name='papertradingaccount',
            name='losing_trades',
            field=models.IntegerField(default=0, help_text='Number of losing trades'),
        ),
        migrations.AddField(
            model_name='papertradingaccount',
            name='winning_trades',
            field=models.IntegerField(default=0, help_text='Number of winning trades'),
        ),
        migrations.AddField(
            model_name='papertradingsession',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if status is ERROR'),
        ),
        migrations.AddField(
            model_name='papertradingsession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, help_text='Last activity timestamp'),
        ),
        migrations.AddField(
            model_name='papertradingsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional session metadata'),
        ),
        migrations.AddField(
            model_name='papertradingsession',
            name='stopped_at',
            field=models.DateTimeField(blank=True, help_text='Session stop timestamp', null=True),
        ),
        migrations.AddField(
            model_name='papertradingsession',
            name='total_trades',
            field=models.IntegerField(default=0, help_text='Total trades in this session'),
        ),
        migrations.AlterField(
            model_name='paperaithoughtlog',
            name='confidence_level',
            field=models.DecimalField(decimal_places=2, help_text='Confidence percentage (0-100)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='paperaithoughtlog',
            name='decision_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold'), ('SKIP', 'Skip')], help_text='Type of decision', max_length=10),
        ),
        migrations.AlterField(
            model_name='paperaithoughtlog',
            name='thought_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique thought identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paperaithoughtlog',
            name='token_address',
            field=models.CharField(help_text='Token contract address', max_length=42),
        ),
        migrations.AlterField(
            model_name='paperperformancemetrics',
            name='largest_loss_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Largest losing trade', max_digits=20),
        ),
        migrations.AlterField(
            model_name='paperperformancemetrics',
            name='largest_win_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Largest winning trade', max_digits=20),
        ),
        migrations.AlterField(
            model_name='paperperformancemetrics',
            name='losing_trades',
            field=models.IntegerField(default=0, help_text='Number of losing trades'),
        ),
        migrations.AlterField(
            model_name='paperperformancemetrics',
            name='period_end',
            field=models.DateTimeField(help_text='Period end timestamp'),
        ),
        migrations.AlterField(
            model_name='paperperformancemetrics',
            name='period_start',
            field=models.DateTimeField(help_text='Period start timestamp'),
        ),
        migrations.AlterField(
            model_name='paperperformancemetrics',
            name='profit_factor',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Ratio of gross profit to gross loss', max_digits=6),
        ),
        migrations.AlterField(
            model_name='paperperformancemetrics',
            name='session',
            field=models.ForeignKey(help_text='Associated trading session', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='paper_trading.papertradingsession'),
        ),
        migrations.AlterField(
            model_name='paperperformancemetrics',
            name='sharpe_ratio',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Risk-adjusted return metric (Sharpe Ratio)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='paperperformancemetrics',
            name='total_pnl_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total P&L as percentage', max_digits=7),
        ),
        migrations.AlterField(
            model_name='paperperformancemetrics',
            name='total_pnl_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total profit/loss in USD', max_digits=20),
        ),
        migrations.AlterField(
            model_name='paperperformancemetrics',
            name='total_trades',
            field=models.IntegerField(default=0, help_text='Total trades in period'),
        ),
        migrations.AlterField(
            model_name='paperperformancemetrics',
            name='win_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Win rate percentage (0-100)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='paperperformancemetrics',
            name='winning_trades',
            field=models.IntegerField(default=0, help_text='Number of winning trades'),
        ),
        migrations.AlterField(
            model_name='paperposition',
            name='account',
            field=models.ForeignKey(help_text='Associated account', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='paper_trading.papertradingaccount'),
        ),
        migrations.AlterField(
            model_name='paperposition',
            name='average_entry_price_usd',
            field=models.DecimalField(decimal_places=8, help_text='Average entry price in USD', max_digits=20),
        ),
        migrations.AlterField(
            model_name='paperposition',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Position close timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='paperposition',
            name='current_price_usd',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Current market price', max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paperposition',
            name='current_value_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current position value', max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paperposition',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Whether position is still open'),
        ),
        migrations.AlterField(
            model_name='paperposition',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='paperposition',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Position open timestamp'),
        ),
        migrations.AlterField(
            model_name='paperposition',
            name='position_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique position identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paperposition',
            name='quantity',
            field=models.DecimalField(decimal_places=18, help_text='Amount held in wei', max_digits=36),
        ),
        migrations.AlterField(
            model_name='paperposition',
            name='realized_pnl_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Realized profit/loss after closing', max_digits=20),
        ),
        migrations.AlterField(
            model_name='paperposition',
            name='token_address',
            field=models.CharField(help_text='Token contract address', max_length=42),
        ),
        migrations.AlterField(
            model_name='paperposition',
            name='token_symbol',
            field=models.CharField(help_text='Token symbol', max_length=20),
        ),
        migrations.AlterField(
            model_name='paperposition',
            name='total_invested_usd',
            field=models.DecimalField(decimal_places=2, help_text='Total amount invested', max_digits=20),
        ),
        migrations.AlterField(
            model_name='paperposition',
            name='unrealized_pnl_usd',
            field=models.DecimalField(decimal_places=2, help_text='Unrealized profit/loss', max_digits=20),
        ),
        migrations.AlterField(
            model_name='paperstrategyconfiguration',
            name='account',
            field=models.ForeignKey(help_text='Associated trading account', on_delete=django.db.models.deletion.CASCADE, related_name='strategy_configs', to='paper_trading.papertradingaccount'),
        ),
        migrations.AlterField(
            model_name='paperstrategyconfiguration',
            name='config_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique configuration identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paperstrategyconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Configuration creation timestamp'),
        ),
        migrations.AlterField(
            model_name='paperstrategyconfiguration',
            name='trading_mode',
            field=models.CharField(choices=[('CONSERVATIVE', 'Conservative'), ('MODERATE', 'Moderate'), ('AGGRESSIVE', 'Aggressive'), ('CUSTOM', 'Custom')], default='MODERATE', help_text='Trading mode', max_length=20),
        ),
        migrations.AlterField(
            model_name='paperstrategyconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='account',
            field=models.ForeignKey(help_text='Associated account', on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='paper_trading.papertradingaccount'),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='actual_amount_out',
            field=models.DecimalField(blank=True, decimal_places=18, help_text='Actual output amount', max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='amount_in_usd',
            field=models.DecimalField(decimal_places=2, help_text='Amount in USD', max_digits=20),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Trade creation timestamp'),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if failed'),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='executed_at',
            field=models.DateTimeField(blank=True, help_text='Trade execution timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='expected_amount_out',
            field=models.DecimalField(decimal_places=18, help_text='Expected output amount', max_digits=36),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='AI trade context (intel level, confidence, reasoning)'),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='mock_block_number',
            field=models.IntegerField(blank=True, help_text='Simulated block number', null=True),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='simulated_gas_cost_usd',
            field=models.DecimalField(decimal_places=2, help_text='Simulated gas cost in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='simulated_gas_price_gwei',
            field=models.DecimalField(decimal_places=2, help_text='Simulated gas price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='simulated_gas_used',
            field=models.IntegerField(help_text='Simulated gas units used'),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='simulated_slippage_percent',
            field=models.DecimalField(decimal_places=2, help_text='Simulated slippage percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current trade status', max_length=20),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='strategy_name',
            field=models.CharField(blank=True, help_text='Strategy that generated this trade', max_length=100),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='token_in_address',
            field=models.CharField(help_text='Input token address', max_length=42),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='token_in_symbol',
            field=models.CharField(help_text='Input token symbol', max_length=20),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='token_out_address',
            field=models.CharField(help_text='Output token address', max_length=42),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='token_out_symbol',
            field=models.CharField(help_text='Output token symbol', max_length=20),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='trade_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique trade identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='trade_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('swap', 'Swap')], help_text='Type of trade', max_length=10),
        ),
        migrations.AlterField(
            model_name='papertradingaccount',
            name='account_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique account identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='papertradingaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Account creation timestamp'),
        ),
        migrations.AlterField(
            model_name='papertradingaccount',
            name='current_balance_usd',
            field=models.DecimalField(decimal_places=2, help_text='Current virtual balance in USD', max_digits=20),
        ),
        migrations.AlterField(
            model_name='papertradingaccount',
            name='initial_balance_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Starting virtual balance in USD', max_digits=20),
        ),
        migrations.AlterField(
            model_name='papertradingaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether account is active'),
        ),
        migrations.AlterField(
            model_name='papertradingaccount',
            name='name',
            field=models.CharField(help_text='Account name', max_length=100),
        ),
        migrations.AlterField(
            model_name='papertradingaccount',
            name='total_trades',
            field=models.IntegerField(default=0, help_text='Total number of trades'),
        ),
        migrations.AlterField(
            model_name='papertradingaccount',
            name='user',
            field=models.ForeignKey(help_text='Account owner', on_delete=django.db.models.deletion.CASCADE, related_name='paper_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='papertradingconfig',
            name='account',
            field=models.OneToOneField(help_text='Associated account', on_delete=django.db.models.deletion.CASCADE, related_name='config', to='paper_trading.papertradingaccount'),
        ),
        migrations.AlterField(
            model_name='papertradingsession',
            name='account',
            field=models.ForeignKey(help_text='Associated trading account', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='paper_trading.papertradingaccount'),
        ),
        migrations.AlterField(
            model_name='papertradingsession',
            name='failed_trades',
            field=models.IntegerField(default=0, help_text='Number of failed trades'),
        ),
        migrations.AlterField(
            model_name='papertradingsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique session identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='papertradingsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Session start timestamp'),
        ),
        migrations.AlterField(
            model_name='papertradingsession',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='RUNNING', help_text='Current session status', max_length=20),
        ),
        migrations.AlterField(
            model_name='papertradingsession',
            name='strategy_config',
            field=models.ForeignKey(help_text='Strategy configuration used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='paper_trading.paperstrategyconfiguration'),
        ),
        migrations.AlterField(
            model_name='papertradingsession',
            name='successful_trades',
            field=models.IntegerField(default=0, help_text='Number of successful trades'),
        ),
        migrations.AddIndex(
            model_name='paperstrategyconfiguration',
            index=models.Index(fields=['account', 'is_active'], name='paper_strat_account_a2c8e3_idx'),
        ),
        migrations.AddIndex(
            model_name='paperstrategyconfiguration',
            index=models.Index(fields=['autopilot_enabled'], name='paper_strat_autopil_e13393_idx'),
        ),
        migrations.AddIndex(
            model_name='paperstrategyconfiguration',
            index=models.Index(fields=['created_at'], name='paper_strat_created_315c42_idx'),
        ),
        migrations.AddField(
            model_name='autopilotlog',
            name='reverses_log',
            field=models.ForeignKey(blank=True, help_text='Previous adjustment this reverses', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='paper_trading.autopilotlog'),
        ),
        migrations.AddField(
            model_name='autopilotlog',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Associated trading session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autopilot_logs', to='paper_trading.papertradingsession'),
        ),
        migrations.AddField(
            model_name='autopilotlog',
            name='strategy_config',
            field=models.ForeignKey(help_text='Associated strategy configuration', on_delete=django.db.models.deletion.CASCADE, related_name='autopilot_logs', to='paper_trading.paperstrategyconfiguration'),
        ),
        migrations.AddField(
            model_name='autopilotperformancesnapshot',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Associated trading session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='paper_trading.papertradingsession'),
        ),
        migrations.AddField(
            model_name='autopilotperformancesnapshot',
            name='strategy_config',
            field=models.ForeignKey(help_text='Associated strategy configuration', on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='paper_trading.paperstrategyconfiguration'),
        ),
        migrations.RemoveField(
            model_name='paperposition',
            name='stop_loss_price',
        ),
        migrations.RemoveField(
            model_name='paperposition',
            name='take_profit_price',
        ),
        migrations.AddIndex(
            model_name='autopilotlog',
            index=models.Index(fields=['strategy_config', 'timestamp'], name='autopilot_l_strateg_94b5cd_idx'),
        ),
        migrations.AddIndex(
            model_name='autopilotlog',
            index=models.Index(fields=['adjustment_type'], name='autopilot_l_adjustm_fc618d_idx'),
        ),
        migrations.AddIndex(
            model_name='autopilotlog',
            index=models.Index(fields=['outcome'], name='autopilot_l_outcome_b7c9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='autopilotlog',
            index=models.Index(fields=['timestamp'], name='autopilot_l_timesta_5a2538_idx'),
        ),
        migrations.AddIndex(
            model_name='autopilotlog',
            index=models.Index(fields=['session', 'timestamp'], name='autopilot_l_session_e80358_idx'),
        ),
        migrations.AddIndex(
            model_name='autopilotperformancesnapshot',
            index=models.Index(fields=['strategy_config', 'timestamp'], name='autopilot_p_strateg_106e87_idx'),
        ),
        migrations.AddIndex(
            model_name='autopilotperformancesnapshot',
            index=models.Index(fields=['autopilot_active'], name='autopilot_p_autopil_3925bf_idx'),
        ),
        migrations.AddIndex(
            model_name='autopilotperformancesnapshot',
            index=models.Index(fields=['win_rate'], name='autopilot_p_win_rat_bf7ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='autopilotperformancesnapshot',
            index=models.Index(fields=['timestamp'], name='autopilot_p_timesta_42f4c1_idx'),
        ),
        migrations.AddIndex(
            model_name='autopilotperformancesnapshot',
            index=models.Index(fields=['session', 'timestamp'], name='autopilot_p_session_f9d155_idx'),
        ),
    ]
