# Generated by Django 5.2.6 on 2025-10-26 19:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0005_autopilotlog_autopilotperformancesnapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperaithoughtlog',
            name='reasoning',
        ),
        migrations.RemoveField(
            model_name='paperaithoughtlog',
            name='risk_assessment',
        ),
        migrations.AddField(
            model_name='paperaithoughtlog',
            name='confidence_percent',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Exact confidence percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paperaithoughtlog',
            name='opportunity_score',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Opportunity assessment score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paperaithoughtlog',
            name='primary_reasoning',
            field=models.TextField(default='Historical record', help_text='Primary reasoning for the decision (1-3 sentences)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paperaithoughtlog',
            name='risk_score',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Risk assessment score (0-100, higher is riskier)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paperaithoughtlog',
            name='confidence_level',
            field=models.CharField(choices=[('VERY_HIGH', 'Very High (90-100%)'), ('HIGH', 'High (70-90%)'), ('MEDIUM', 'Medium (50-70%)'), ('LOW', 'Low (30-50%)'), ('VERY_LOW', 'Very Low (<30%)')], help_text='Confidence level category', max_length=20),
        ),
        migrations.AlterField(
            model_name='paperaithoughtlog',
            name='decision_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold'), ('SKIP', 'Skip'), ('STOP_LOSS', 'Stop Loss'), ('TAKE_PROFIT', 'Take Profit')], help_text='Type of decision made', max_length=20),
        ),
        migrations.AlterField(
            model_name='paperaithoughtlog',
            name='token_address',
            field=models.CharField(help_text='Token being analyzed', max_length=42),
        ),
    ]
