# Generated by Django 5.2.6 on 2025-11-10 17:14

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0005_paperorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyRun',
            fields=[
                ('strategy_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this strategy run', primary_key=True, serialize=False)),
                ('strategy_type', models.CharField(choices=[('DCA', 'Dollar Cost Averaging'), ('GRID', 'Grid Trading'), ('TWAP', 'Time-Weighted Average Price'), ('VWAP', 'Volume-Weighted Average Price'), ('CUSTOM', 'Custom Strategy')], help_text='Type of trading strategy', max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Strategy-specific configuration parameters')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', help_text='Current execution status', max_length=20)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Completion percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('current_step', models.CharField(blank=True, default='', help_text='Current execution step description', max_length=200)),
                ('total_orders', models.IntegerField(default=0, help_text='Total number of orders planned', validators=[django.core.validators.MinValueValidator(0)])),
                ('completed_orders', models.IntegerField(default=0, help_text='Number of successfully completed orders', validators=[django.core.validators.MinValueValidator(0)])),
                ('failed_orders', models.IntegerField(default=0, help_text='Number of failed orders', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_invested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total USD amount invested so far', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('average_entry', models.DecimalField(decimal_places=18, default=Decimal('0.00'), help_text='Average entry price across all orders', max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current profit/loss in USD', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When strategy was created')),
                ('started_at', models.DateTimeField(blank=True, help_text='When strategy execution started', null=True)),
                ('paused_at', models.DateTimeField(blank=True, help_text='When strategy was paused', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When strategy completed successfully', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When strategy was cancelled', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='User notes about this strategy')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if strategy failed')),
                ('account', models.ForeignKey(help_text='Account executing this strategy', on_delete=django.db.models.deletion.CASCADE, related_name='strategy_runs', to='paper_trading.papertradingaccount')),
            ],
            options={
                'verbose_name': 'Strategy Run',
                'verbose_name_plural': 'Strategy Runs',
                'db_table': 'paper_strategy_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyOrder',
            fields=[
                ('id', models.BigAutoField(help_text='Auto-incrementing ID', primary_key=True, serialize=False)),
                ('order_sequence', models.IntegerField(help_text='Order sequence number within strategy (1, 2, 3...)', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this link was created')),
                ('order', models.ForeignKey(help_text='The actual order', on_delete=django.db.models.deletion.CASCADE, related_name='strategy_links', to='paper_trading.paperorder')),
                ('strategy_run', models.ForeignKey(help_text='Strategy this order belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='strategy_orders', to='paper_trading.strategyrun')),
            ],
            options={
                'verbose_name': 'Strategy Order',
                'verbose_name_plural': 'Strategy Orders',
                'db_table': 'paper_strategy_orders',
                'ordering': ['order_sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='strategyrun',
            index=models.Index(fields=['account', 'status'], name='paper_strat_account_48dc55_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyrun',
            index=models.Index(fields=['strategy_type', 'status'], name='paper_strat_strateg_44d5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyrun',
            index=models.Index(fields=['status', 'created_at'], name='paper_strat_status_5e3ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyrun',
            index=models.Index(fields=['account', 'strategy_type'], name='paper_strat_account_1321ba_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyorder',
            index=models.Index(fields=['strategy_run', 'order_sequence'], name='paper_strat_strateg_79d5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyorder',
            index=models.Index(fields=['order', 'created_at'], name='paper_strat_order_i_f0a3ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategyorder',
            unique_together={('strategy_run', 'order'), ('strategy_run', 'order_sequence')},
        ),
    ]
