# Generated by Django 5.2.6 on 2025-11-29 17:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_trading", "0005_backtestrun_backtestresult_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperstrategyconfiguration",
            name="dca_num_purchases",
            field=models.IntegerField(
                default=10,
                help_text="Number of DCA purchases (2-100)",
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="paperstrategyconfiguration",
            name="grid_price_range_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Grid price range percentage (1-50%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("1.00")),
                    django.core.validators.MaxValueValidator(Decimal("50.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="paperstrategyconfiguration",
            name="twap_execution_window_hours",
            field=models.IntegerField(
                default=6,
                help_text="TWAP execution window in hours (1-24)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(24),
                ],
            ),
        ),
        migrations.AddField(
            model_name="paperstrategyconfiguration",
            name="twap_num_intervals",
            field=models.IntegerField(
                default=12,
                help_text="Number of TWAP execution intervals (2-100)",
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="paperstrategyconfiguration",
            name="vwap_execution_window_hours",
            field=models.IntegerField(
                default=6,
                help_text="VWAP execution window in hours (1-24)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(24),
                ],
            ),
        ),
        migrations.AddField(
            model_name="paperstrategyconfiguration",
            name="vwap_num_intervals",
            field=models.IntegerField(
                default=12,
                help_text="Number of VWAP execution intervals (2-100)",
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="paperstrategyconfiguration",
            name="dca_interval_hours",
            field=models.IntegerField(
                default=24,
                help_text="Hours between DCA purchases (1-168)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(168),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="paperstrategyconfiguration",
            name="enable_dca",
            field=models.BooleanField(
                default=False, help_text="Enable Dollar Cost Averaging strategy"
            ),
        ),
        migrations.AlterField(
            model_name="paperstrategyconfiguration",
            name="enable_grid",
            field=models.BooleanField(
                default=False, help_text="Enable Grid Trading strategy"
            ),
        ),
        migrations.AlterField(
            model_name="paperstrategyconfiguration",
            name="enable_twap",
            field=models.BooleanField(
                default=False, help_text="Enable Time-Weighted Average Price strategy"
            ),
        ),
        migrations.AlterField(
            model_name="paperstrategyconfiguration",
            name="enable_vwap",
            field=models.BooleanField(
                default=False, help_text="Enable Volume-Weighted Average Price strategy"
            ),
        ),
        migrations.AlterField(
            model_name="paperstrategyconfiguration",
            name="grid_num_levels",
            field=models.IntegerField(
                default=10,
                help_text="Number of grid levels (3-50)",
                validators=[
                    django.core.validators.MinValueValidator(3),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
    ]
