# Generated by Claude on 2025-10-27

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):
    """
    Add intel_level field to PaperStrategyConfiguration.
    
    This migration adds an intelligence level field (1-10) to the strategy
    configuration model, allowing the dashboard to control bot intelligence.
    """

    dependencies = [
        ('paper_trading', '0006_remove_paperaithoughtlog_reasoning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='intel_level',
            field=models.IntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10)
                ],
                help_text='Intelligence level (1-10) controlling bot decision-making behavior'
            ),
        ),
        migrations.AddIndex(
            model_name='paperstrategyconfiguration',
            index=models.Index(fields=['intel_level'], name='paper_strat_intel_l_idx'),
        ),
    ]