# Generated by Django 5.2.6 on 2025-11-29 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_trading", "0006_add_twap_vwap_config_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paperstrategyconfiguration",
            name="dca_num_purchases",
        ),
        migrations.RemoveField(
            model_name="paperstrategyconfiguration",
            name="grid_price_range_percent",
        ),
        migrations.RemoveField(
            model_name="paperstrategyconfiguration",
            name="twap_num_intervals",
        ),
        migrations.AddField(
            model_name="paperstrategyconfiguration",
            name="twap_num_chunks",
            field=models.IntegerField(
                default=12,
                help_text="Number of TWAP execution chunks (2-100)",
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="paperstrategyconfiguration",
            name="dca_interval_hours",
            field=models.IntegerField(
                default=2,
                help_text="Hours between each DCA buy (1-168 hours = 1 week max)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(168),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="paperstrategyconfiguration",
            name="enable_dca",
            field=models.BooleanField(
                default=False,
                help_text="Enable Dollar Cost Averaging (DCA) strategy - spreads buys over time",
            ),
        ),
        migrations.AlterField(
            model_name="paperstrategyconfiguration",
            name="enable_grid",
            field=models.BooleanField(
                default=False,
                help_text="Enable Grid Trading strategy - places multiple orders at different price levels",
            ),
        ),
        migrations.AlterField(
            model_name="paperstrategyconfiguration",
            name="grid_num_levels",
            field=models.IntegerField(
                default=7,
                help_text="Number of grid price levels (3-20)",
                validators=[
                    django.core.validators.MinValueValidator(3),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
    ]
