# Generated by Django 5.2.6 on 2025-10-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0007_add_intel_level_to_strategy_config'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paperstrategyconfiguration',
            name='paper_strat_intel_l_idx',
        ),
    ]
