# Generated by Django 5.2.6 on 2025-11-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0007_add_strategy_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperstrategyconfiguration',
            name='dca_interval_hours',
        ),
        migrations.RemoveField(
            model_name='paperstrategyconfiguration',
            name='dca_num_intervals',
        ),
        migrations.RemoveField(
            model_name='paperstrategyconfiguration',
            name='enable_dca',
        ),
        migrations.RemoveField(
            model_name='paperstrategyconfiguration',
            name='enable_grid',
        ),
        migrations.RemoveField(
            model_name='paperstrategyconfiguration',
            name='enable_twap',
        ),
        migrations.RemoveField(
            model_name='paperstrategyconfiguration',
            name='enable_vwap',
        ),
        migrations.RemoveField(
            model_name='paperstrategyconfiguration',
            name='grid_num_levels',
        ),
        migrations.RemoveField(
            model_name='paperstrategyconfiguration',
            name='grid_profit_target_percent',
        ),
    ]
