# Generated by Django 5.2.6 on 2025-11-11 19:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0008_remove_paperstrategyconfiguration_dca_interval_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='dca_interval_hours',
            field=models.IntegerField(default=2, help_text='Hours between each DCA buy (1-168 hours = 1 week max)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='dca_num_intervals',
            field=models.IntegerField(default=5, help_text='Number of DCA buy intervals (2-20)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='enable_dca',
            field=models.BooleanField(default=False, help_text='Enable Dollar Cost Averaging (DCA) strategy - spreads buys over time'),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='enable_grid',
            field=models.BooleanField(default=False, help_text='Enable Grid Trading strategy - places multiple orders at different price levels'),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='enable_twap',
            field=models.BooleanField(default=False, help_text='Enable TWAP (Time-Weighted Average Price) strategy'),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='enable_vwap',
            field=models.BooleanField(default=False, help_text='Enable VWAP (Volume-Weighted Average Price) strategy'),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='grid_num_levels',
            field=models.IntegerField(default=7, help_text='Number of grid price levels (3-20)', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='paperstrategyconfiguration',
            name='grid_profit_target_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.0'), help_text='Target profit per grid level in percent (0.1-10.0%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('10.0'))]),
        ),
    ]
