# Generated by Django 5.2.6 on 2025-11-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "paper_trading",
            "0009_paperstrategyconfiguration_dca_interval_hours_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="paperposition",
            name="average_entry_price_usd",
            field=models.DecimalField(
                decimal_places=18, help_text="Average entry price in USD", max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="paperposition",
            name="current_price_usd",
            field=models.DecimalField(
                decimal_places=18, help_text="Current market price", max_digits=20
            ),
        ),
    ]
