# Generated by Django 5.2.6 on 2025-11-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0010_add_max_position_per_token'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paperstrategyconfiguration',
            name='paper_strat_max_pos_token_idx',
        ),
        migrations.RemoveField(
            model_name='paperstrategyconfiguration',
            name='max_position_size_per_token_percent',
        ),
    ]
