# Generated by Django 5.2.6 on 2025-11-02 16:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0011_remove_paperstrategyconfiguration_paper_strat_max_pos_token_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertrade',
            name='actual_amount_out',
            field=models.DecimalField(blank=True, decimal_places=18, default=None, help_text='Actual output amount', max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='amount_in',
            field=models.DecimalField(decimal_places=18, default=Decimal('0'), help_text='Amount in (wei)', max_digits=36),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='amount_in_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount in USD', max_digits=20),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='expected_amount_out',
            field=models.DecimalField(decimal_places=18, default=Decimal('0'), help_text='Expected output amount', max_digits=36),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='simulated_gas_cost_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Simulated gas cost in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='simulated_gas_price_gwei',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Simulated gas price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='simulated_slippage_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='Simulated slippage percentage', max_digits=5),
        ),
    ]
