# Generated by Django 5.2.6 on 2025-09-14 11:45

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('trading', '0002_position_created_at_position_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureImportance',
        ),
        migrations.AlterModelOptions(
            name='decisionfeature',
            options={'ordering': ['context', '-importance_score', 'category', 'name']},
        ),
        migrations.RenameField(
            model_name='decisionfeature',
            old_name='confidence',
            new_name='confidence_level',
        ),
        migrations.RenameField(
            model_name='thoughtlog',
            old_name='priority_level',
            new_name='priority',
        ),
        migrations.RemoveField(
            model_name='decisionfeature',
            name='contribution_score',
        ),
        migrations.RemoveField(
            model_name='decisionfeature',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='decisionfeature',
            name='processed_value',
        ),
        migrations.RemoveField(
            model_name='decisionfeature',
            name='processing_time_ms',
        ),
        migrations.RemoveField(
            model_name='decisionfeature',
            name='raw_value',
        ),
        migrations.RemoveField(
            model_name='decisionfeature',
            name='source',
        ),
        migrations.RemoveField(
            model_name='decisionfeature',
            name='threshold_values',
        ),
        migrations.RemoveField(
            model_name='decisionfeature',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='decisionmetrics',
            name='execution_cost_usd',
        ),
        migrations.RemoveField(
            model_name='decisionmetrics',
            name='opportunity_cost_usd',
        ),
        migrations.RemoveField(
            model_name='decisionmetrics',
            name='pnl_30min_usd',
        ),
        migrations.RemoveField(
            model_name='decisionmetrics',
            name='pnl_5min_usd',
        ),
        migrations.RemoveField(
            model_name='decisionmetrics',
            name='risk_accuracy_score',
        ),
        migrations.RemoveField(
            model_name='decisionmetrics',
            name='timing_score',
        ),
        migrations.RemoveField(
            model_name='modelperformance',
            name='average_return_percent',
        ),
        migrations.RemoveField(
            model_name='modelperformance',
            name='decisions_made',
        ),
        migrations.RemoveField(
            model_name='modelperformance',
            name='risk_accuracy',
        ),
        migrations.RemoveField(
            model_name='modelperformance',
            name='total_opportunities',
        ),
        migrations.RemoveField(
            model_name='modelperformance',
            name='trades_executed',
        ),
        migrations.RemoveField(
            model_name='modelperformance',
            name='vs_benchmark_percent',
        ),
        migrations.RemoveField(
            model_name='thoughtlog',
            name='alternative_outcomes',
        ),
        migrations.RemoveField(
            model_name='thoughtlog',
            name='counterfactuals',
        ),
        migrations.RemoveField(
            model_name='thoughtlog',
            name='detailed_analysis',
        ),
        migrations.RemoveField(
            model_name='thoughtlog',
            name='max_gas_price_gwei',
        ),
        migrations.RemoveField(
            model_name='thoughtlog',
            name='max_slippage_percent',
        ),
        migrations.RemoveField(
            model_name='thoughtlog',
            name='negative_signals',
        ),
        migrations.RemoveField(
            model_name='thoughtlog',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='thoughtlog',
            name='positive_signals',
        ),
        migrations.RemoveField(
            model_name='thoughtlog',
            name='primary_reasoning',
        ),
        migrations.RemoveField(
            model_name='thoughtlog',
            name='recommended_amount',
        ),
        migrations.RemoveField(
            model_name='thoughtlog',
            name='risk_factors',
        ),
        migrations.AddField(
            model_name='decisionfeature',
            name='importance_score',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Feature importance score (0-1)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='decisionfeature',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw data used to compute this feature'),
        ),
        migrations.AddField(
            model_name='decisionfeature',
            name='value_bool',
            field=models.BooleanField(blank=True, help_text='Boolean feature value', null=True),
        ),
        migrations.AddField(
            model_name='decisionfeature',
            name='value_numeric',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Numeric feature value', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='decisionfeature',
            name='value_text',
            field=models.TextField(blank=True, help_text='Text/categorical feature value'),
        ),
        migrations.AddField(
            model_name='decisionmetrics',
            name='max_drawdown_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Maximum drawdown percentage', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='decisionmetrics',
            name='pnl_1hr_usd',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='PnL after 1 hour (USD)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='decisionmetrics',
            name='pnl_7d_usd',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='PnL after 7 days (USD)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='modelperformance',
            name='average_pnl_per_decision_usd',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Average PnL per decision (USD)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='modelperformance',
            name='successful_decisions',
            field=models.PositiveIntegerField(default=0, help_text='Number of successful decisions'),
        ),
        migrations.AddField(
            model_name='modelperformance',
            name='total_decisions',
            field=models.PositiveIntegerField(default=0, help_text='Total decisions made in this period'),
        ),
        migrations.AddField(
            model_name='modelperformance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='thoughtlog',
            name='alternative_scenarios',
            field=models.JSONField(blank=True, default=list, help_text='Alternative scenarios considered'),
        ),
        migrations.AddField(
            model_name='thoughtlog',
            name='reasoning_steps',
            field=models.JSONField(default=[], help_text='Step-by-step reasoning process as structured data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thoughtlog',
            name='recommended_position_size_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recommended position size in USD', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='thoughtlog',
            name='recommended_stop_loss_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recommended stop loss percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='thoughtlog',
            name='recommended_take_profit_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recommended take profit percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='thoughtlog',
            name='risk_concerns',
            field=models.JSONField(blank=True, default=list, help_text='Risk concerns identified during analysis'),
        ),
        migrations.AlterField(
            model_name='decisioncontext',
            name='token',
            field=models.ForeignKey(help_text='Primary token being analyzed', on_delete=django.db.models.deletion.CASCADE, related_name='decision_contexts', to='trading.token'),
        ),
        migrations.AlterField(
            model_name='decisionfeature',
            name='category',
            field=models.CharField(choices=[('TECHNICAL', 'Technical Indicators'), ('FUNDAMENTAL', 'Fundamental Analysis'), ('SENTIMENT', 'Market Sentiment'), ('RISK', 'Risk Metrics'), ('LIQUIDITY', 'Liquidity Analysis'), ('TIMING', 'Timing Factors'), ('PORTFOLIO', 'Portfolio Context'), ('MARKET', 'Market Conditions')], max_length=15),
        ),
        migrations.AlterField(
            model_name='decisionfeature',
            name='name',
            field=models.CharField(help_text="Feature name (e.g., 'rsi_14', 'holder_concentration')", max_length=100),
        ),
        migrations.AlterField(
            model_name='decisionmetrics',
            name='pnl_24hr_usd',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='PnL after 24 hours (USD)', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the learning session started'),
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='average_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average confidence level', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='average_decision_latency_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Average decision latency (ms)', null=True),
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='average_execution_latency_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Average execution latency (ms)', null=True),
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='custom_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Additional performance metrics'),
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='performance_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique performance identifier', unique=True),
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='period_end',
            field=models.DateTimeField(help_text='End of the performance measurement period'),
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='period_start',
            field=models.DateTimeField(help_text='Start of the performance measurement period'),
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='sharpe_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Sharpe ratio', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='time_window',
            field=models.CharField(choices=[('HOUR', '1 Hour'), ('DAY', '1 Day'), ('WEEK', '1 Week'), ('MONTH', '1 Month'), ('QUARTER', '1 Quarter'), ('YEAR', '1 Year')], max_length=10),
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='total_pnl_usd',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Total PnL for this period (USD)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='win_rate_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Win rate percentage', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='thoughtlog',
            name='confidence_percent',
            field=models.DecimalField(decimal_places=2, help_text='Confidence in this decision (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='thoughtlog',
            name='decision_outcome',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold'), ('SKIP', 'Skip'), ('EMERGENCY_EXIT', 'Emergency Exit')], max_length=15),
        ),
        migrations.AlterField(
            model_name='thoughtlog',
            name='key_factors',
            field=models.JSONField(blank=True, default=list, help_text='Key factors that influenced the decision'),
        ),
        migrations.AddIndex(
            model_name='modelperformance',
            index=models.Index(fields=['sharpe_ratio'], name='analytics_m_sharpe__7b8d62_idx'),
        ),
    ]
